// Mocks generated by Mockito 5.0.8 from annotations
// in example_flutter1/test/screens/login/login_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:example_flutter1/models/user_model.dart' as _i2;
import 'package:example_flutter1/screens/login/login_controller.dart';
import 'package:example_flutter1/services/user_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/mockito.dart';

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUserModel extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i3.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel()))
          as _i4.Future<_i2.UserModel>);
}
